<footer class="footer">
    <div class="container-page d-flex flex-column justify-content-center align-items-center hstack gap-3">
        <div class="footer-developer d-flex flex-column align-items-center flex-md-row">
            <span><span class="name">Laignelet David</span> - Développeur web en formation</span>
            <span class="footer-text ms-2">Tous droits réservés &#169;</span>
        </div>
        <div class="footer-data d-flex flex-column align-items-center hstack gap-3">
            <div class="footer-study-content d-flex flex-column flex-md-row align-items-center">
                <span>Coched by</span><img src="<?= ROOT_URL ?>/documents/images/studi.png" alt="" class="studi">
            </div>
            <span class="footer-source">Source photos : Laignelet David & www.pixabay.com</span>
        </div>
    </div>
</footer>