<header class="header container-fluid">
    <div class="container-page d-flex">    
        <nav class="navbar d-flex flex-row justify-content-between container-fluid">
            <a href="./index.php" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera2" viewBox="0 0 16 16">
                    <path d="M5 8c0-1.657 2.343-3 4-3V4a4 4 0 0 0-4 4z"/>
                    <path d="M12.318 3h2.015C15.253 3 16 3.746 16 4.667v6.666c0 .92-.746 1.667-1.667 1.667h-2.015A5.97 5.97 0 0 1 9 14a5.972 5.972 0 0 1-3.318-1H1.667C.747 13 0 12.254 0 11.333V4.667C0 3.747.746 3 1.667 3H2a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1h.682A5.97 5.97 0 0 1 9 2c1.227 0 2.367.368 3.318 1zM2 4.5a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0zM14 8A5 5 0 1 0 4 8a5 5 0 0 0 10 0z"/>
                </svg>
                Le Pied à l'Objectf
            </a>

            <div class="menu">
                <ul class="navbar-nav d-flex flex-row justify-content-between align-items-center container-fluid">
                <li class="nav-item"><a href="./event.php">évenements</a></li>
                <li class="nav-item"><a href="#">blog</a></li>
                <li class="nav-item"><a href="#">contact</a></li>
                </ul>
            </div>
        </nav>
    </div>

</header>