<header class="header container-fluid">
    <div class="container-page d-flex">    
        <nav class="navbar d-flex justify-content-between container-fluid">
            <a href="<?= ROOT_URL ?>/index.php" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera2" viewBox="0 0 16 16">
                    <path d="M5 8c0-1.657 2.343-3 4-3V4a4 4 0 0 0-4 4z"/>
                    <path d="M12.318 3h2.015C15.253 3 16 3.746 16 4.667v6.666c0 .92-.746 1.667-1.667 1.667h-2.015A5.97 5.97 0 0 1 9 14a5.972 5.972 0 0 1-3.318-1H1.667C.747 13 0 12.254 0 11.333V4.667C0 3.747.746 3 1.667 3H2a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1h.682A5.97 5.97 0 0 1 9 2c1.227 0 2.367.368 3.318 1zM2 4.5a.5.5 0 1 0-1 0 .5.5 0 0 0 1 0zM14 8A5 5 0 1 0 4 8a5 5 0 0 0 10 0z"/>
                </svg>
                Le Pied à l'Objectif
            </a>

            <div class="menu header-desk-view">
                <ul class="navbar-nav flex-row justify-content-between align-items-center container-fluid hstack gap-3">
                    <li class="nav-item"><a href="<?= ROOT_URL ?>/index.php?page=event">évenements</a></li>
                    <li class="nav-item"><a href="#">blog</a></li>
                    <li class="nav-item"><a href="#">contact</a></li>
                </ul>
            </div>

            <div class="header-mobile-view">
                <button class="btn btn-primary btn-outline-secondary" type="button" data-bs-toggle="offcanvas" data-bs-target="#staticBackdrop" aria-controls="staticBackdrop">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                </button>
            </div>
        </nav>
    </div>
    
    <div class="offcanvas offcanvas-start" data-bs-backdrop="static" tabindex="-1" id="staticBackdrop" aria-labelledby="staticBackdropLabel">
    <div class="offcanvas-header">
        <span class="offcanvas-title" id="staticBackdropLabel">Le Pied à l'Objectif</span>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="navbar-nav flex-column align-items-start container-fluid hstack gap-3">
            <li class="nav-item"><a href="<?= ROOT_URL ?>/index.php">accueil</a></li>
            <li class="nav-item"><a href="<?= ROOT_URL ?>/index.php?page=event">évenements</a></li>
            <li class="nav-item"><a href="#">blog</a></li>
            <li class="nav-item"><a href="#">contact</a></li>
        </ul>
    </div>
    </div>

</header>
