<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le Pied à l'Objectif est un club photo basé à Monstaunes sur la communauté du Cagire Garonne Salat. Sortie photo - Stage photo - Atelier thématiques">
    <title>Le pied à l'objectif</title>

    <link rel="stylesheet" href="css/main.css" type="text/css"/>
    <link rel="stylesheet" href="https://use.typekit.net/skf2lbk.css">
    
</head>
<body>
<?php

include ('./layout/header.phtml');
include ($content);
include ('./layout/footer.phtml');

?>

</body>
</html>