<!DOCTYPE html>
<html lang="fr" class="container-fluid">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le Pied à l'Objectif est un club photo basé à Monstaunes sur la communauté du Cagire Garonne Salat. Sortie photo - Stage photo - Atelier thématiques">
    <meta name="googlebot" content="none">
    <meta name="googlebot-news" content="nosnippet">

    <title>Le Pied à l'Objectif</title>

    <link rel="stylesheet" href="<?= ROOT_URL ?>/css/main.css" type="text/css"/>
    <link rel="stylesheet" href="https://use.typekit.net/skf2lbk.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="<?= ROOT_URL ?>/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

</head>
<body>
<?php

include ('./layout/header.phtml');
include ($content);
include ('./layout/footer.phtml');

?>

</body>
</html>