<main>
    <div class="container-page">

        <section id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="<?= ROOT_URL ?>/documents/carousel/london-1200.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="<?= ROOT_URL ?>/documents/carousel/street-1200.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                <img class="d-block w-100" src="<?= ROOT_URL ?>/documents/carousel/paris.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev carousel-control" href="#carouselExampleControls" role="button" data-bs-slide="prev" data-bs-target="#carouselExampleControls">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                    <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                </svg>
            </a>
            <a class="carousel-control-next carousel-control" href="#carouselExampleControls" role="button" data-bs-slide="next" data-bs-target="#carouselExampleControls">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>
            </a>
        </section>

        <section class="word d-flex flex-column align-items-center">
            <h2 class="word-title title-page">Faisons de la photo ensemble</h2>
            <div class="word-content d-flex flex-column flex-md-row align-items-md-center">
                <div class="word-text-content">
                    <p class="word-text">La pratique de la photographie est souvent une activitée solitaire, mais quand c'est le cas, progresser demande du temps. Le but du Pied à l'Objectif est de pratiquer la photo à plusieurs afin de s'aider à progresser</p>
                    <p class="word-text">L'association propose ses activités à tous et toutes et nous espérons bientôt ouvrir une section "Jeunes Photographes" afin d'acompagner des jeunes dans la pratique de la photographie.</p>
                </div>
                <img src="<?= ROOT_URL ?>/documents/images/word-photo.jpg" alt="Le pied à l'objectif - Faisons de la photo ensembel" class="word-img">
            </div>
        </section>

        <section class="reinsurance d-flex flex-column align-items-center">
            <h2 class="reinsurance-title title-page">Les actions de l'association</h2>
            <div class="reinsurance-content-list">
                <ul class="reinsurance-list d-flex flex-column flex-md-row justify-content-between align-items-center hstack gap-3">
                    <li class="reinsurance-item d-flew flex-column">
                        <div class="reinsurance-content-title d-flex flex-row align-items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-image" viewBox="0 0 16 16">
                                <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                                <path d="M2.002 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-12zm12 1a1 1 0 0 1 1 1v6.5l-3.777-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12V3a1 1 0 0 1 1-1h12z"/>
                            </svg>
                            <h3 class="reinsurance-item-title">Sorties</h3>
                        </div>
                        <p class="reinsurance-item-text">De manière régulière, nous effecturons des sorties photo de groupe sur des thèmes différnets, nature, architecture, urbex,...</p>

                    </li>
                    <li class="reinsurance-item d-flew flex-column">
                        <div class="reinsurance-content-title d-flex flex-row  align-items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera" viewBox="0 0 16 16">
                            <path d="M15 12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h1.172a3 3 0 0 0 2.12-.879l.83-.828A1 1 0 0 1 6.827 3h2.344a1 1 0 0 1 .707.293l.828.828A3 3 0 0 0 12.828 5H14a1 1 0 0 1 1 1v6zM2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2z"/>
                            <path d="M8 11a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                        </svg>
                            <h3 class="reinsurance-item-title">Stages</h3>
                        </div>
                        <p class="reinsurance-item-text">Les stages seront l'occasion de travailler des techniques de prise de vue et d'apprendfre à maîtriser son appareil photo</p>

                    </li>
                    <li class="reinsurance-item d-flew flex-column">
                        <div class="reinsurance-content-title d-flex flex-row  align-items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-easel" viewBox="0 0 16 16">
                            <path d="M8 0a.5.5 0 0 1 .473.337L9.046 2H14a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-1.85l1.323 3.837a.5.5 0 1 1-.946.326L11.092 11H8.5v3a.5.5 0 0 1-1 0v-3H4.908l-1.435 4.163a.5.5 0 1 1-.946-.326L3.85 11H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h4.954L7.527.337A.5.5 0 0 1 8 0zM2 3v7h12V3H2z"/>
                        </svg>
                            <h3 class="reinsurance-item-title">Soirées</h3>
                        </div>
                        <p class="reinsurance-item-text">De manière très régulière, l'association organisera des soirée de projection, ou nous étudirons les photos prises lors des sorties ou des stages.</p>

                    </li>
                </ul>
            </div>
        </section>

        <article class="article d-flex flex-column align-items-center">
            <h2 class="article-title title-page">Nos actualités</h2>
            
            <div class="article-content d-flex flex-column align-self-stretch flex-sm-row justify-content-around hstack gap-3">
                <div class="card">
                    <img class="card-img-top" src="<?= ROOT_URL ?>/documents/images/event.JPG" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Sortie montage de printemps</h5>
                        <p class="card-text">Comme tous les ans, nous organisons une première sortie photo en montagne pour prendre l'air après ces mois d'hiver.</p>
                        <a href="./index.php?page=event" class="btn btn-primary">En savoir +</a>
                    </div>
                </div>
           
                <div class="card">
                    <img class="card-img-top" src="<?= ROOT_URL ?>/documents/images/portrait.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Atelier portrait</h5>
                        <p class="card-text">Nous avons réalisé un atelier portrait avec deux manequins qui se sont prètés au jeux, ce fût une très bonne expérience !</p>
                        <a href="#" class="btn btn-primary">En savoir +</a>
                    </div>
                </div>
            
            </div>
        </article>

        <section class="where d-flex flex-column align-items-center">
            <h2 class="where-title title-page">Où nous trouver ?</h2>
            <div class="where-content d-flex">
                <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1tEliw4LnaHsJPwBT9ELn9kPfbVSag7U&ehbc=2E312F" width="640" height="480"></iframe>
                <p class="where-text">Le Pied à l'Objectif est basé à Montsaunes dans les Comminges. Situé aux pieds des Pyrénées, ce secteur nous offre un terrain de jeu vaste et varié, où chacun pourras laisser s'exprimer sa créativité.</p>
                <p class="where-text">Pour tout renseignements sur les activitées de l'association où pour y adhérer contactez-nous</p>
                <button class="btn btn-secondary"><a href="#" class="where-contact">Contactez-nous</a></button>
            </div>
        </section>
        
    </div>
</main>