<main>
    <div class="container-page">

        <section id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="<?= ROOT_URL ?>/documents/carousel/london-1200.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="<?= ROOT_URL ?>/documents/carousel/street-1200.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                <img class="d-block w-100" src="<?= ROOT_URL ?>/documents/carousel/paris.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev carousel-control" href="#carouselExampleControls" role="button" data-bs-slide="prev" data-bs-target="#carouselExampleControls">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                    <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                </svg>
            </a>
            <a class="carousel-control-next carousel-control" href="#carouselExampleControls" role="button" data-bs-slide="next" data-bs-target="#carouselExampleControls">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>
            </a>
        </section>

        <section class="word d-flex flex-column align-items-center">
            <h2 class="word-title title-page">Faisons de la photo ensemble</h2>
            <div class="word-content d-flex flex-column flex-md-row align-items-md-center">
                <div class="word-text-content">
                    <p class="word-text">La pratique de la photographie est souvent une activitée solitaire, mais quand c'est le cas, progresser demande du temps. Le but du Pied à l'Objectif est de pratiquer la photo à plusieurs afin de s'aider à progresser</p>
                    <p class="word-text">L'association propose ses activités à tous et toutes et nous espérons bientôt ouvrir une section "Jeunes Photographes" afin d'acompagner des jeunes dans la pratique de la photographie.</p>
                </div>
                <img src="<?= ROOT_URL ?>/documents/images/word-photo.jpg" alt="Le pied à l'objectif - Faisons de la photo ensembel" class="word-img">
            </div>
        </section>

        <section class="reinsurance d-flex flex-column align-items-center">
            <h2 class="reinsurance-title title-page">Les actions de l'association</h2>
            <div class="reinsurance-content-list">
                <ul class="reinsurance-list d-flex flex-colmun justify-content-between align-items-center">
                    <li class="reinsurance-item d-flew flex-column">
                        <h3 class="reinsurance-item-title">Bla</h3>
                        <p class="reinsurance-item-text"></p>

                    </li>
                    <li class="reinsurance-item d-flew flex-column">
                        <h3 class="reinsurance-item-title">Bla</h3>
                        <p class="reinsurance-item-text"></p>

                    </li>
                    <li class="reinsurance-item d-flew flex-column">
                        <h3 class="reinsurance-item-title">Bla</h3>
                        <p class="reinsurance-item-text"></p>

                    </li>
                </ul>
            </div>
        </section>

        <article class="article d-flex flex-column align-items-center">
            <h2 class="article-title title-page">Nos actualités</h2>
            
            <div class="article-content d-flex flex-column justify-content-around">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="./index.php?page=event" class="btn btn-primary">En savoir +</a>
                    </div>
                </div>
           
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">En savoir +</a>
                    </div>
                </div>
            
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">En savoir +</a>
                    </div>
                </div>
            </div>
        </article>

        <section class="where d-flex flex-column align-items-center">
            <h2 class="where-title title-page">Où nous trouver ?</h2>
            <div class="where-content d-flex">
                <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1tEliw4LnaHsJPwBT9ELn9kPfbVSag7U&ehbc=2E312F" width="640" height="480"></iframe>
                <p class="where-text">Le Pied à l'Objectif est basé à Montsaunes dans les Comminges. Situé aux pieds des Pyrénées, ce secteur nous offre un terrain de jeu vaste et varié, où chacun pourras laisser s'exprimer sa créativité.</p>
                <p class="where-text">Pour tout renseignements sur les activitées de l'association où pour y adhérer contactez-nous</p>
                <button class="btn btn-secondary"><a href="#" class="where-contact">Contactez-nous</a></button>
            </div>
        </section>
        
    </div>
</main>