<main>
    <div class="container-page">

        <section id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="./documents/carousel/london-1200.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="./documents/carousel/street-1200.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                <img class="d-block w-100" src="./documents/carousel/paris.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </section>

        <section class="word">
            <h2 class="word-title title-page">Faisons de la photo ensemble</h2>
            <div class="word-content">
                <p class="word-text">La pratique de la photographie est souvent une activitée solitaire, mais quand c'est le cas, progresser demande du temps. Le but du Pied à l'Objectif est de pratiquer la photo à plusieurs afin de s'aider à progresser</p>
                <p class="word-text">L'association propose ses activités à tous et toutes et nous espérons bientôt ouvrir une section "Jeunes Photographes" afin d'acompagner des jeunes dans la pratique de la photographie.</p>
                <img src="./documents/images/word-photo.jpg" alt="Le pied à l'objectif - Faisons de la photo ensembel" class="word-img">
            </div>
        </section>

        <section class="reinsurance">
            <h2 class="reinsurance-title title-page">Les actions de l'association</h2>
            <div class="reinsurance-content-list">
                <ul class="reinsurance-list d-flex flex-row justify-content-between align-items-center">
                    <li class="reinsurance-item d-flew flex-column">
                        <h3 class="reinsurance-item-title"></h3>
                        <p class="reinsurance-item-text"></p>

                    </li>
                    <li class="reinsurance-item d-flew flex-column">
                        <h3 class="reinsurance-item-title"></h3>
                        <p class="reinsurance-item-text"></p>

                    </li>
                    <li class="reinsurance-item d-flew flex-column">
                        <h3 class="reinsurance-item-title"></h3>
                        <p class="reinsurance-item-text"></p>

                    </li>
                </ul>
            </div>
        </section>
        <article class="article">
            <h2 class="article-title title-page">Nos actualités</h2>
            
            <div class="article-content d-flex flex-row justify-content-around">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
           
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
        </article>

        <section class="where">
            <h2 class="where-title title-page">Où nous trouver ?</h2>
            <div class="where-content d-flex">
                <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1tEliw4LnaHsJPwBT9ELn9kPfbVSag7U&ehbc=2E312F" width="640" height="480"></iframe>
                <p class="where-text">Le Pied à l'Objectif est basé à Montsaunes dans les Comminges. Situé aux pieds des Pyrénées, ce secteur nous offre un terrain de jeu vaste et varié, où chacun pourras laisser s'exprimer sa créativité.</p>
                <p class="where-text">Pour tout renseignements sur les activitées de l'association où pour y adhérer contactez-nous</p>
                <button class="btn btn-secondary"><a href="#" class="where-contact">Contactez-nous</a></button>
            </div>
        </section>
        
    </div>
</main>