<main>
    <div class="container-page">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= ROOT_URL ?>/index.php">Accueil</a></li>
                <li class="breadcrumb-item"><a href="#">Evènements</a></li>
                <li class="breadcrumb-item active" aria-current="page">Sortie montage de printemps</li>
            </ol>
        </nav>

        <article class="event">
            <div class="event-header d-flex flex-column align-items-center mb-5">
                <h2 class="event-title mb-3">Sortie montage de printemps</h2>
                <img src="<?= ROOT_URL ?>/documents/images/event.JPG" alt="" class="event-picture">
            </div>

            <nav id="navbar-event" class="nav-scroll navbar bg-secondary p-2 text-dark bg-opacity-50 px-3 mb-3">
                <ul class="nav nav-pills d-flex justify-content-around">
                    <li class="nav-item">
                        <a class="nav-link" href="#scrollspyWhat">Description</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#scrollspyWho">Qui ?</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#scrollspyWhen">Quand ?</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#scrollspyWhere">Où ?</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#scrollspyHow">Comment ?</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#scrollspyReserv">Réserver</a>
                    </li>
                </ul>
            </nav>

            <div data-bs-spy="scroll" data-bs-target="#navbar-event" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" class="scrollspy-event bg-light p-3 rounded-2" tabindex="0">
                <div class="event-what d-flex flex-column mb-4">
                    <h3 class="event-what-title title-page">Description de la sortie</h3>
                    <p class="event-text">Comme tous les ans, nous organisons une première sortie photo en montagne pour prendre l'air après les mois d'hiver. Cette année il n'y a pas de thème ou de technique inposé, chacun de nous pourras faire les photos qu'il désire, paysage, macro, portrait,...</p>
                    <p class="event-text">Une dizaine de jours après cette sortie, nous ferons évidement une soirée spéciale pour projeter les photos comme nous en avons l'habitude, je vous préviendrai à l'avance.</p>
                    <p class="event-text"  id="scrollspyWhat">Afin de préserver la montage et garder des espaces vides et vièrges, nous avons décidé de limiter à 30 participants cette année, alors pensez à réserver vos palces !</p>
                </div>
                <div class="event-who d-flex flex-column  mb-4">
                    <h3 class="event-who-title title-page">Qui est concerné ?</h3>
                    <p class="event-text"  id="scrollspyWho">Afin d'ajouter un peu de convivialité, de partage, et de la matière pour les portraitistes, nous proposons aux adhérents de venir en famille. </p>
                </div>
                <div class="event-when d-flex flex-column  mb-4">
                    <h3 class="event-when-title title-page">Quand ?</h3>
                    <p class="event-text"  id="scrollspyWhen">La sortie se fera le samedi 8 avril 2023 à 8h au point de rendez-vous. S'il doit y avoir des problèmes météo à cette date, nous prévoyons de la décaler au samedi 22 avril 2023 à 8h même heure, même lieu.</p>
                </div>
                <div class="event-where d-flex flex-column  mb-4">
                    <h3 class="event-where-title title-page">Où ?</h3>
                    <iframe class="event-where-map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d23359.27886746731!2d0.880917983285591!3d42.959103970505765!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12a8e9bb04a07349%3A0x6e224c4f0134cacc!2sparking%20de%20la%20fontaine%20de%20l&#39;ours!5e0!3m2!1sfr!2sfr!4v1667455257160!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    <p class="event-text">Nous irons au col de la Paloumère au dessus d'Arbas. Vous trouverez sur la carte le point de rendez-vous qui est le parking du départ de la randonnée.</p>
                    <p class="event-text"  id="scrollspyWhere">Nous vous laissons gérer ensemble le covoiturage pour ceux qui le désire.</p>
                </div>
                <div class="event-how d-flex flex-column  mb-4">
                    <h3 class="event-how-title title-page">Déroulement de la journée</h3>
                    <p class="event-text">Une fois que nous nous serons tous retrouvés au parking, il faudra faire une petite randonnée sur chemin carrossable (4x4) d'environ 1h, c'est très facile, pour rejoindre l'estive de la Paloumère, notre camp de base pour la journée. De ce point les plus courageux et sportifs pourront rejoindre les crètes pour de plus beaux paysages.</p>
                    <p class="event-text">Prévoyez un pique-nique pour le midi, l'association ne fournira pas le repas ni les boissons.</p>
                    <p class="event-text">Une fois arrivée sur l'estive, chacun sera libre de faire ce qu'il veux, nous souhaitons juste nous retrouver tous à 12h30 pour partager le repas ensemble.</p>
                    <p class="event-text">Pour l'après-midi chacun sera également libre d'aller où bon lui semble et de faire les photos qu'il désire, et le retour commun se fera à 16h pour être au parking à 17h.</p>
                    <p class="event-text"  id="scrollspyHow">Cependant, pour ceux qui le désire, vous pourrez rester plus longtemps, voir y passer la nuit. Ce sera l'occasion de faire de très belles photos de coucher de soleil, la vue est dégagée, ou de ciel nocturne (si la météo le permet). Par contre pour ceux qui décident de rester l'association déclinera toute respoinsablilité en cas d'accident, et vous devrez prévoir votre matériel de bivouac.</p>
                </div>
                <div class="event-btns d-flex flex-row justify-content-between justify-content-md-evenly hstack gap-3  mb-5" id="scrollspyReserv">
                    <button class="btn btn-secondary event-btn" data-bs-toggle="modal" data-bs-target="#contactModal"><a href="#">renseignements</a></button>
                    <button class="btn btn-secondary event-btn" data-bs-toggle="modal" data-bs-target="#reservModal"><a href="#">reserver</a></button>
                </div>
            </div>
        </article>

    </div>
</main>